#!/bin/bash
# Update the package lists for upgrades and new package installations
sudo apt-get update -y
# Install nginx
sudo apt-get install -y nginx
# Remove the default nginx configuration
sudo rm /etc/nginx/sites-available/default
# Create a new default nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        return 200 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart

